### ISSUE TITLE
Video Display

### ISSUE THREAD

**Issue by joyce-wu** [MRuvinshteyn/didactic-guacamole#1]
After clicking on a category, it might be confusing to see a lot of boxes filled with text about videos. Maybe load some thumbnails to include images.

**Comment by RuvinshteynM** [comment]
There won't be too many boxes like the image posted in the README, it will be a simplified version that will be much easier to look at and understand. The idea of thumbnails is wonderful, however, and we will try to incorporate that if possible. Thank you!
